### PR TITLE
Completed project 1 for johnt3_rsromero

### PR DESCRIPTION
**Pull request by jtokarowski**
Collaborated on one computer for the majority of the work on this project, and opted to upload all of the files at once rather than commit individual pieces from one machine or the other.

### CODE REVIEW

**Comment by lapets** [comment]
There is a conflict in your pull request. Your README.md file should be in your own group subdirectory. The root README.md file should remain the same as the one in the skeleton code. Could you please adjust your pull request?

**Comment by jtokarowski** [comment]
Conflicts should now be resolved

**Comment by jtokarowski** [comment]
Accidentally closed the pull request, should now be ready to merge.

**Comment by jtokarowski** [comment]
Ok one last try- readme should match the most up to date readme in the master branch

**Pull request merged**
